let product = [
    {
        'id' : 1,
        'productName' : 'Apple MacBook Air',
        'price' : 35900,
        'description' : "The Apple MacBook Air (M2, 2023) combines power, portability, and elegance in one sleek design. With the next-generation M2 chip, it offers incredible speed, smooth multitasking, and enhanced graphics performance for professional workflows or casual use. Whether you're a student, creative professional, or tech enthusiast, the MacBook Air's 13.6-inch Retina display delivers sharp, vibrant visuals while its ultra-lightweight design ensures you can take it anywhere.",
        'image' : ['images/product/product1/a.jpg','images/product/product1/b.jpg','images/product/product1/c.jpg'],
        'spec' : 'M2, 2023',
        'category' : 'laptop'
    },
    {
        'id' : 2,
        'productName' : 'Apple MacBook Pro 16-inch',
        'price' : 74900,
        'description' : "The MacBook Pro 16-inch (2023) with the M2 Max chip is a powerhouse laptop designed for professionals who demand top-tier performance. Whether you're working on complex software development, 3D rendering, or large video projects, the M2 Max chip offers extraordinary speed and efficiency.",
        'image' : ['images/product/product2/a.jpg','images/product/product2/b.jpg','images/product/product2/c.jpg'],
        'spec' : 'M2 Max Chip, 2023',
        'category' : 'laptop',
    },
    {
        'id' : 3,
        'productName' : 'ASUS ZenBook Pro 16X OLED',
        'price' : 59000,
        'description' : "The ASUS ZenBook Pro 16X OLED is a high-performance laptop designed for creative professionals. It features a 16-inch OLED display with 4K resolution, delivering stunning visuals and color accuracy. Powered by Intel's latest Core i9 processor and NVIDIA GeForce RTX 4060 graphics, it offers exceptional performance for multitasking, design work, and multimedia editing. The laptop is also equipped with a precision dial, a unique input device that allows users to easily adjust settings for creative tasks like photo and video editing.",
        'image' : ['images/product/product3/a.jpg','images/product/product3/b.jpg','images/product/product3/c.jpg'],
        'spec' : 'UX7602',
        'category' : 'laptop',
    },
    {
        'id' : 4,
        'productName' : 'ASUS ROG Strix G15',
        'price' : 43000,
        'description' : "The ASUS ROG Strix G15 is a gaming laptop designed for intense gaming and content creation. It boasts a 15.6-inch Full HD display with a 165Hz refresh rate for smooth visuals during gaming. Powered by AMD Ryzen 9 7000 series processors and NVIDIA GeForce RTX 4070 graphics, this laptop offers high-end performance, making it ideal for gaming, streaming, and video editing. The Strix G15 also features a customizable RGB keyboard and excellent thermal management, ensuring optimal performance during long gaming sessions.",
        'image' : ['images/product/product4/a.jpg','images/product/product4/b.jpg','images/product/product4/c.jpg'],
        'spec' : 'G513RM, 2025',
        'category' : 'laptop',
    },
    {
        'id' : 5,
        'productName' : 'Dell XPS 15',
        'price' : 58000,
        'description' : "The Dell XPS 15 is a premium ultrabook designed for both power and portability. It comes with a stunning 15.6-inch 4K OLED display, delivering vibrant colors and deep contrast. Powered by the latest Intel Core i9 13th Gen processor and NVIDIA GeForce RTX 4060 graphics, it’s perfect for creative professionals, gamers, and multitaskers. The laptop offers 16GB of RAM and a 1TB SSD, providing both speed and ample storage for demanding tasks. The slim profile and all-metal build offer a sleek and durable design.",
        'image' : ['images/product/product5/a.jpg','images/product/product5/b.jpg','images/product/product5/c.jpg'],
        'spec' : 'XPS 15 9530,2025',
        'category' : 'laptop',
    },
    {
        'id' : 6,
        'productName' : 'Dell Alienware m17 R6',
        'price' : 50000,
        'description' : "The Alienware m17 R5 is a high-performance gaming laptop. It features a large 17.3-inch Full HD display with a 360Hz refresh rate, making it ideal for fast-paced gaming. It is powered by an Intel Core i7 processor (12th Gen) and comes with NVIDIA GeForce RTX 3080 Ti graphics, ensuring that AAA games run smoothly at high settings. This laptop also boasts up to 32GB of DDR5 RAM and 1TB SSD storage, making it suitable for both gaming and creative workloads like video editing. The design is futuristic, with customizable RGB lighting and excellent cooling technology.",
        'image' : ['images/product/product6/a.jpg','images/product/product6/b.jpg','images/product/product6/c.jpg'],
        'spec' : '6980HX',
        'category' : 'laptop',
    },
    {
        'id' : 7,
        'productName' : 'iPhone 15',
        'price' : 42000,
        'description' : "The iPhone 15 Pro Max is the top-tier model of the iPhone 15 series, offering cutting-edge technology and premium features. It boasts a 6.7-inch Super Retina XDR OLED display with ProMotion and Always-On features. The phone is powered by the new A17 Pro chip, offering faster performance and improved energy efficiency. The iPhone 15 Pro Max is equipped with a 48MP main camera, 120Hz ProMotion display, and advanced cinematic video capabilities. It also introduces USB-C for faster charging and data transfer. The design features titanium sides, making it lighter and more durable.",
        'image' : ['images/product/product7/a.jpg','images/product/product7/b.jpg','images/product/product7/c.jpg'],
        'spec' : 'Pro Max',
        'category' : 'smartphone',
    },
    {
        'id' : 8,
        'productName' : 'iPhone 14',
        'price' : 36000,
        'description' : "The iPhone 14 Pro Max is designed for those who want the best of Apple’s smartphone technology, including a stunning camera system, powerful performance, and the innovative Dynamic Island feature. It's an excellent choice for heavy users, content creators, and tech enthusiasts who need cutting-edge features.",
        'image' : ['images/product/product8/a.jpg','images/product/product8/b.jpg','images/product/product8/c.jpg'],
        'spec' : 'Pro Max',
        'category' : 'smartphone',
    },
    {
        'id' : 9,
        'productName' : 'Samsung Galaxy S23 Ultra',
        'price' : 39900,
        'description' : "The Samsung Galaxy S23 Ultra is a flagship smartphone that boasts powerful performance, a stunning 6.8-inch Dynamic AMOLED display, and the most advanced camera system Samsung has ever put in a phone. It's perfect for users who demand top-tier features, whether it's gaming, media consumption, or photography.",
        'image' : ['images/product/product9/a.jpg','images/product/product9/b.jpg','images/product/product9/c.jpg'],
        'spec' : 'Qualcomm Snapdragon 8 Gen 2',
        'category' : 'smartphone',
    },
    {
        'id' : 10,
        'productName' : 'Samsung Galaxy A54 5G',
        'price' : 12990,
        'description' : "The Samsung Galaxy A54 5G is a mid-range smartphone that offers impressive performance, a solid AMOLED display, and reliable cameras at a more affordable price point. It's perfect for everyday use, whether for social media, light gaming, or entertainment.",
        'image' : ['images/product/product10/a.jpg','images/product/product10/b.jpg','images/product/product10/c.jpg'],
        'spec' : 'Exynos 1380',
        'category' : 'smartphone',
    },
    {
        'id' : 11,
        'productName' : 'Xiaomi 14 Pro',
        'price' : 29990,
        'description' : "The Xiaomi 14 Pro is the flagship model of the Xiaomi 14 series, offering top-tier performance, a stunning AMOLED display, and powerful camera capabilities. With a sleek design and advanced internals, it's tailored for users who demand high performance, whether for gaming, photography, or multitasking.",
        'image' : ['images/product/product11/a.jpg','images/product/product11/b.jpg','images/product/product11/c.jpg'],
        'spec' : 'Qualcomm Snapdragon 8 Gen 3',
        'category' : 'smartphone',
    },
    {
        'id' : 12,
        'productName' : 'Xiaomi 13T',
        'price' : 18990,
        'description' : "The Xiaomi 13T is a premium mid-range phone that offers excellent value for money, featuring Leica-enhanced cameras, a smooth 120Hz OLED display, and solid performance. It's a great choice for users looking for flagship-like features without the flagship price tag.",
        'image' : ['images/product/product12/a.jpg','images/product/product12/b.jpg','images/product/product12/c.jpg'],
        'spec' : 'MediaTek Dimensity 9200+',
        'category' : 'smartphone',
    },
    {
        'id' : 13,
        'productName' : 'JBL Pulse 5',
        'price' : 7990,
        'description' :"The JBL Pulse 5 is the latest addition to JBL's Pulse series, known for its stunning light show features combined with powerful sound. It delivers 360° sound that fills any room or outdoor space. Equipped with a large rechargeable battery, it can play up to 12 hours on a single charge. Its colorful LED light show can sync with the beat of the music, creating a dynamic visual experience. Perfect for parties, outdoor events, or home use.",
        'image' : ['images/product/product13/a.jpg','images/product/product13/b.jpg','images/product/product13/c.jpg'],
        'spec' : 'JBL PartyBoost',
        'category' : 'speaker',
    },
    {
        'id' : 14,
        'productName' : 'JBL Charge 5',
        'price' : 5990,
        'description' :"The JBL Charge 5 is the latest version of the famous Charge series, delivering outstanding audio performance with deep bass and clear sound. With an IP67 rating, it's completely waterproof and dustproof, making it ideal for beach days or poolside hangouts. The Charge 5 also doubles as a power bank, allowing you to charge other devices on the go. It features JBL Bass Radiators and PartyBoost, enabling you to pair multiple Charge 5 units for an even bigger sound.",
        'image' : ['images/product/product14/a.jpg','images/product/product14/b.jpg','images/product/product14/c.jpg'],
        'spec' : 'JBL PartyBoost',
        'category' : 'speaker',
    },
    {
        'id' : 15,
        'productName' : 'Sony SRS-XV900',
        'price' : 14990,
        'description' :"The Sony SRS-XV900 is a flagship portable speaker in Sony’s X-series, offering incredible sound and impressive volume levels. This speaker is designed to bring vibrant, high-quality audio with 360-degree sound and powerful bass. It features Sony's X-Balanced speaker drivers for a more dynamic sound, and Mega Bass for deeper bass. Additionally, the built-in LED lights create an immersive atmosphere that can be customized to match your music. It's perfect for parties, large gatherings, or outdoor events, with a robust IP67 waterproof rating.",
        'image' : ['images/product/product15/a.jpg','images/product/product15/b.jpg','images/product/product15/c.jpg'],
        'spec' : 'X-series',
        'category' : 'speaker',
    },
    {
        'id' : 16,
        'productName' : 'Sony SRS-XG500',
        'price' : 10990,
        'description' :"The Sony SRS-XG500 is a high-performance portable speaker built for both deep bass and clear vocals. It features the same X-Balanced speaker technology that maximizes sound pressure, making it ideal for large gatherings or outdoor events. The SRS-XG500 has a robust, rugged design with a metal grill and comes with built-in LED lights for extra flair. It also offers a longer battery life of up to 30 hours, and quick charging features make it a great companion for all-day listening sessions. It’s also highly portable with a retractable handle for easy transport.",
        'image' : ['images/product/product16/a.jpg','images/product/product16/b.jpg','images/product/product16/c.jpg'],
        'spec' : 'X-Balanced',
        'category' : 'speaker',
    },
    {
        'id' : 17,
        'productName' : 'Beats Studio Pro',
        'price' : 11900,
        'description' :"The Beats Studio Pro is a high-end over-ear headphone, designed for those who want both premium sound quality and an immersive experience. Featuring adaptive noise cancellation (ANC) and a more customizable fit, these headphones deliver superb audio performance with Pure Adaptive Noise Cancelling and Spatial Audio support. With an upgraded design, the Studio Pro comes with a longer battery life (up to 40 hours) and high-quality materials. Perfect for long commutes, flights, or anyone who values comfort and sound precision, the Beats Studio Pro is a top choice for audiophiles.",
        'image' : ['images/product/product17/a.jpg','images/product/product17/b.jpg','images/product/product17/c.jpg'],
        'spec' : 'H1 chip',
        'category' : 'headset',
    },
    {
        'id' : 18,
        'productName' : 'Beats Fit Pro',
        'price' : 6990,
        'description' :"The Beats Fit Pro is a compact and versatile in-ear headphone designed for active individuals. These true wireless earbuds are equipped with Active Noise Cancelling and Transparency mode, offering a balanced experience between immersion and situational awareness. The wingtip design ensures a secure fit during workouts or runs, while the Apple H1 chip provides fast pairing and integration with Apple devices. Ideal for fitness enthusiasts, commuters, or those on the go, the Beats Fit Pro combines performance and style in a small, comfortable package.",
        'image' : ['images/product/product18/a.jpg','images/product/product18/b.jpg','images/product/product18/c.jpg'],
        'spec' : 'H1 chip',
        'category' : 'headset',
    },
    
]